(define (json-get prop json)
  (cond ((null? json) '())
        ((equal? prop (caar json)) (car (cdar json)))
        (else (json-get prop (cdr json)))))

(define (json-find prop json) 
  (letrec 
    ((result '())
     (define (find prop json) 
       (define (check-prop pair)
         (cond ((null? pair) #f)
               ((not (list? pair)) #f)
               ((equal? (car pair) prop) (set! result (cadr pair)))
               ((list? (car pair)) (find prop (car pair)))
               (else #f)))
       (define (check-value pair) 
         (cond ((null? pair) #f)
               ((not (list? pair)) #f)
               (else (if (list? (cdr pair)) (find prop (cdr pair)) #f))))
       (cond 
         ((null? json) #f)
         ((check-prop json) #t)
         ((check-prop (car json)) #t)
         ((check-value (car json)) #t)
         (else (find prop (cdr json))))))

    (find prop json)
    result))

(define (string-join items separator)
  (cond ((null? items) "")
        (else (if (null? (cdr items))
                (car items)
                (concat (car items) separator (string-join (cdr items) separator))))))

(define (sexp->json sexp) 
  (cond ((null? sexp) "null")
        ((and (pair? sexp) (symbol? (car sexp)) (equal? (length sexp) 2)) 
         (concat "\"" (symbol->string (car sexp)) "\": " (sexp->json (cadr sexp)))
        )
        ((list? sexp) (concat "{" (string-join (map sexp->json sexp) ", ") "}"))
        ((string? sexp) (concat "\"" sexp "\""))
        ((number? sexp) (number->string sexp))
        ((symbol? sexp) (symbol->string sexp))
        ((boolean? sexp) (if sexp "true" "false"))
        (else (error (concat "Sorry don't know how to jsonify that " (print sexp))))
))

